version: '3.8'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PhanHoangQuanzzz123@"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./src/main/resources/dbinit.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/usr/src/app/entrypoint.sh"]
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "8443:8443"
    restart: unless-stopped

volumes:
  mssql_data:
